### PR TITLE
Update Link to WLED-GUI in compatible-software.md

### PR DESCRIPTION
**Pull request by w00000dy**
I changed my GitHub name, so this is an update for that link.

### CODE REVIEW

**Comment by blazoncek** [comment]
Why, oh, why?! 😄

**Comment by w00000dy** [comment]
I did not like the old name for quite a long time and now I thought it was time to change it. My old name gave me some Minecraft kiddy vibes.

The link https://github.com/WoodyLetsCode/WLED-GUI would still work, but I changed the link just to be sure and don't confuse anyone.

**Comment by Aircoookie** [comment]
And people were unsure about the number of o's Aircoookie was written with already 😂

**Comment by w00000dy** [comment]
I'm sorry, but just the name _woody_ is taken everywhere. 😭

**Pull request merged**
