### PR TITLE
Remove all mentions of copyright infringements

### PR DESCRIPTION
**Pull request by WeeJeWel**
The chinese company 'Athom' infringes the trademark of the Dutch company Athom, which owns the trademark on their name in EU and US within the Smart Home market. 

Lawsuits are ongoing in removing all their products from said markets. It is highly confusing for customers. Even on Reddit people are saying 'don't buy from Athom, they make crap' when they are referring to the Chinese copycat, which harms the honest European company (https://athom.com).

I have removed all mentions of their products from the WLED documentation.

### CODE REVIEW

**Comment by blazoncek** [comment]
Hi. I do not want to sound as if I want to endorse Chinese copycats, but before we remove any content please provide any kind of proof of this litigation.

**Comment by WeeJeWel** [comment]
I understand that absolutely. Let me ask our legal department and get back to you.

**Comment by Aircoookie** [comment]
Hi, and first of all thank you for providing evidence of the likely trademark infringement! I am obviously not a lawyer nor a judge so I am in no position to assess whether the claim is justified, though on first glance it certainly seems to be.
Once there is a court order or similar binding legal decision, please let me or @blazoncek know and we will immediately merge this.

Still, transparency is very important to me, so at this time I am willing to add a visually striking disclaimer, for example the following, above the list on the compatible controllers page:

> **Warning** Products listed below under the name "Athom" are offered by the Chinese company ATHOM Technology Co., Ltd., which is not affiliated in any way with the European company Athom B.V., makers of the Homey smart home platform. There is an ongoing legal process against ATHOM Technology Co., Ltd. for possible trademark infringement.

Alternatively, I could add an asterisk * to every mention of the name Athom and a similar disclaimer to the bottom of each page where it is managed. Which do you prefer?

**Comment by WeeJeWel** [comment]
Thank you so much for considering. I am not sure if there will ever be a lawsuit _because_ the company is not established in the EU/US. We will however pursue every reseller based within our jurisdictions.

I think the warning is very nice. Let's go with the first option! Thank you so much.

**Comment by WeeJeWel** [comment]
Thanks for placing the warning.

**Pull request closed without merging**
