### PR TITLE
Update compatible-hardware.md

### PR DESCRIPTION
**Pull request by stanleyondrus**
Fix incorrect category - LedBoxV2 comes pre-installed and is fully-contained
Fixed QuinLED's broken table - taking 4 rows.

### CODE REVIEW

**Comment by blazoncek** [comment]
I know you work hard on your project but please do not reorder listed items unnecessarily.

**Comment by stanleyondrus** [comment]
Dear blazoncek,

I believe that WLED has a neutral and objective community, with no bias. However, for the past few months I am being unfairly targeted by "intermittech" (creator of QuinLED), who keeps reorganizing my LedBoxV2 to a different category on the wiki, truncating all the text, such that my board is not visible to public.

First time he did that in [3c5e735](https://github.com/Aircoookie/WLED/wiki/Compatible-hardware/3c5e735d31adf325448a9b9de40865cef8ed85cf)
I put myself politely back [7b55a60](https://github.com/Aircoookie/WLED/wiki/Compatible-hardware/7b55a60aa106a5efbe74507b6c5676e35ee1f9b5)
Then he removed me again in [e598316](https://github.com/Aircoookie/WLED/wiki/Compatible-hardware/e598316cd457810e65a37ff696b7c478a5f77011)
So I fixed it one more time [ec3a8a0](https://github.com/Aircoookie/WLED/wiki/Compatible-hardware/ec3a8a07e6a38d2c553eb65689f1aea63fdabab2)

All of this was happening without any notice or contact from his side on the old WLED GitHub wiki, and I assumed that this problem will not persist on the new [wiki](https://kno.wled.ge/basics/compatible-hardware/).

However, I can see that my board is now again reorganized to the absolute bottom of the table, which would not be a big deal on its own, but it is deceptively in a wrong category! My board comes with WLED pre-installed, and is fully setup. It is not just "compatible" board that you can "install WLED to if you have a FTDI programmer", which makes a huge difference.

I always considered makers community a huge family where we help each other out. There is no place for this type of unfair destructive marketing tricks, so I believe you will go again through my commit and see that I am just trying to fix incorrect information.

Best regards,
Stanley

**Comment by blazoncek** [comment]
I am grateful that you brought this subject up.
This is exactly what I was observing.
Still, I think @Aircoookie should be the one judging what happens on WLED.

**Comment by Aircoookie** [comment]
Hi, first off all, I'm sorry for misattributing your board to the wrong section - the `https://stanleyprojects.com/projects/ledbox_v2/` page was down at the time and this was my best judgement given the description: "It is fully compatible with WLED and sound reactive WLED fork".

I will check the commit history, I don't want to blame anyone here. I deeply trust Quindor ("intermittech"), and he did notify me at one point that he has edited the article to make it fairer in his opinion, and put the QuinLED boards to the top, since they are in widespread use and well supported by him, and I agreed with that judgement. I'm sorry if you fell victim to that. Maybe it would be the most fair towards everyone to set the order either alphabetically or chronologically, so that a particular position in the list does not convey (dis-)endorsement.

**Comment by Aircoookie** [comment]
Ok, no one is at fault here :)

It seems like the entry for LedBoxV2 was just moved between the `ESP8266/ESP32 boards` section (where you initially placed and subsequently restored it) and the `Useful boards and addons` section. ESP8266/ESP32 section was originally meant for dev boards (like NodeMCU and Wemos D1) while `Useful boards` was meant for boards that incorporate more than that (specific hardware useful for running WLED, e.g. mic, levelshifter, fuses...). As such, your board, in my personal opinion, would have fitted better in that category (and the QuinLED boards were in that category as well).

This point is moot though since with the new categories it is clear that your board belongs in the `Controllers with WLED pre-installed` category.
I am open in that I am very conflicted about what order to place the different entries though - even with an alphabetic list a viewer is much more likely to consider the first few options. On the other hand, it would be the fairest option. "First come first serve" (chronological order of first addition to the wiki page) would also be fair, but lead to absurd situations where e.g. the QuinLED Dig Uno would be at the top of the page, while the Dig Quad is further down.
I'm actually not sure if I want to convey any sort of endorsement on the compatible hardware page, since there are better outlets for that. Still I don't want a new user to just buy the first item on the list just because its name starts with `A`, but I also  can't possibly assume the role of fairly ranking the overall "goodness" of different boards when I have not even personally tested some of them. I know that everyone would like to see their own project as fair up as possible in the list, so I will go with an alphabetical order for now. I'd be happy about more discussion regarding the optimal order for hardware projects :)

**Comment by intermittech** [comment]
Just wanted to chime in here too, I apologize if you felt deliberately targeted @stanleyondrus that was certainly not my intention. Those edits happened during a time where a lot of people where trying to put their boards at the top of the list or in the wrong categories to try and make them appear quicker then the others.

My actions where just to try and correct that and at least put everything in their right categories (admittedly as I saw them) and in somewhat of a correct order where I indeed did put the longest standing projects (including mine) back to how they where organized before.

Still, it remained a sort of mess and I did speak to @Aircoookie about that we needed a better way to edit the list or rather find a better way to present it as a whole but because of time and such to this date it has remained at it was.

So again, my apologies if you felt targeted, certainly not my intention!

**Comment by stanleyondrus** [comment]
I'm also sorry for being a bit salty. My point was not to play a victim card and point fingers. If there is a problem with something I post, I am more than welcome to receive a constructive feedback and correction. I do not mind being on the bottom of the list, it just felt a bit weird that my board was multiple times moved in a way such that my description text was not visible, so I must admit that it felt intentional.

However, I'm glad that we got a chance to discuss it, and now I see that was not the case. There are no hard feeling from my side.

I wish you all good luck and keep up the amazing work!

**Pull request merged**
